### ISSUE TITLE
Where is the wasm file?

### ISSUE THREAD

**Issue by Zentendo** [ClickSimply/duktape-vm#1]
Hi, this library looks great but I'm a bit confused. Where is the `.wasm` binary file? You claim to support WebAssembly with asm.js fallback but I only see js files at the moment. The Emscripten compiled WASM binary seems performance critical and using `ccall` / `cwrap`.

**Comment by only-cliches** [comment]
The WASM file is embedded into the javascript directly as a `Uint8Array`.

You can see the array in the unminified code [here](https://github.com/ClickSimply/duktape-vm/blob/9d7ea37837bd599e46444cc8285670f226da2ee8/build/duktape-vm.js#L239).

Also if you search the minified code for `var wasmBinary` you can find it pretty easily.
